server {
    listen 80 default_server;
    server_name jscraft.work;

    location / {
        return 200 '<!DOCTYPE html><html><body><h1>jscraft.work</h1></body></html>';
        add_header Content-Type text/html;
    }
}
